---
version: "3"
services:
 devopsdb:
   image: mmunna431/dockerproject:dbimage
   ports:
     - "3306:3306"

 application:
   image: mmunna431/dockerproject:appimage
   ports:
     - "2345:8080"
   depends_on:
     - "devopsdb"
